### PR TITLE
Added EfficientNet -- duplicate to ensure the tests run

### PR DESCRIPTION
**Pull request by sarthakpati**
Fixes #ISSUE_NUMBER

## Proposed Changes

- 

## Checklist

- [ ] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [ ] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [ ] Non-breaking change (would not break existing functionality): please provide as many details as possible for any breaking change 
- [ ] Function/class source code documentation added/updated
- [ ] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/CBICA/GaNDLF/blob/master/GANDLF/version.py)
- [ ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/CBICA/GaNDLF/blob/master/pyproject.toml) file 
- [ ] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [ ] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/CBICA/GaNDLF); if coverage is reduced, please give explanation

### CODE REVIEW

**Comment by Geeks-Sid** [comment]
I figured why the test are failing, its a problem with input data within the test.

**Comment by sarthakpati** [comment]
> I figured why the test are failing, its a problem with input data within the test.

Actually, I was trying `[32,32,16]` to see if the CI runner worked, because `[32,32,32]` runs out of memory for EfficientNet. 😄

**Comment by Geeks-Sid** [comment]
> > I figured why the test are failing, its a problem with input data within the test.
> 
> Actually, I was trying `[32,32,16]` to see if the CI runner worked, because `[32,32,32]` runs out of memory for EfficientNet. smile

Not unexpected, efficientnet was made for 2D images for a reason.

**Comment by sarthakpati** [comment]
Closed in favor of https://github.com/Sofia-Mouchtaris/GaNDLF/pull/1

**Pull request closed without merging**
