### PR TITLE
M3D-CAM integration for training/validation

### LINKED ISSUE #5: Add attention maps
**Is your feature request related to a problem? Please describe.**
Interpretability in DL training is critical and would be very nice to have in GaNDLF.

**Describe the solution you'd like**
Integrate [M3d-Cam](https://github.com/MECLabTUDA/M3d-Cam) into the training/inference process.

**Describe alternatives you've considered**
Open to other suggestions.

**Additional context**
Also requested by @gastouna

### PR DESCRIPTION
**Pull request by Karol-G**
Fixes #5

## Proposed Changes
- Integrated M3D-CAM into the validation loop of training_loop.py

## Checklist

- [X] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [X] My PR is based from the refactor branch
- [X] Non-breaking change (would not break existing functionality): if changes breaks current code, please provide as many details as possible
- [ ] Function/class source code documentation added/updated
- [ ] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [ ] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [ ] Tests added or modified to cover the changes
- [ ] Integration tests passed locally by running `pytest`

### CODE REVIEW

**Comment by sarthakpati** [comment]
Awesome show, @Karol-G! Could you also please add `medcam` as a dependency in `setup.py` and also some related documentation?

**Comment by Karol-G** [comment]
You mean to docs/usage.md on how to use medcam?

**Comment by Karol-G** [comment]
I have added some usage documentation.

**Comment by sarthakpati** [comment]
LGTM, @Geeks-Sid?

**Review by Geeks-Sid — APPROVED** [review]

**Comment by Geeks-Sid** [comment]
looks great. Merge when you're ready.

**Comment by sarthakpati** [comment]
Done!

@Karol-G: will follow up via email regarding the paper. 😄

**Pull request merged**
